# Generated by Django 5.1.3 on 2025-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="early_completion",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="on_time_completions",
        ),
        migrations.RemoveField(
            model_name="demand",
            name="overdue_demands",
        ),
        migrations.AddField(
            model_name="team",
            name="early_completion",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="on_time_completions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="overdue_demands",
            field=models.IntegerField(default=0),
        ),
    ]
