# Generated by Django 5.2.4 on 2025-08-10 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_demand_early_completion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="time_completed",
        ),
        migrations.RemoveField(
            model_name="demandeditrequest",
            name="status",
        ),
        migrations.RemoveField(
            model_name="notifications",
            name="is_read",
        ),
        migrations.AlterField(
            model_name="capacity",
            name="capacity_hours",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(15.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="capacitychangerequest",
            name="new_capacity",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(15.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demands",
                to="core.team",
            ),
        ),
        migrations.AlterField(
            model_name="demanddailyallocation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_allocations_by_team",
                to="core.team",
            ),
        ),
    ]
