# Generated by Django 5.2.4 on 2025-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_demand_time_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="allocation_mode",
            field=models.CharField(
                choices=[
                    ("squeeze", "squeeze"),
                    ("even", "even")
                ],
                default="even",
                max_length=10,
            ),
        ),
    ]
