# Generated by Django 5.2.4 on 2025-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_demand_allocation_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="allocation_mode",
            field=models.CharField(
                choices=[("squeeze", "squeeze"), ("even", "even")],
                default="even",
                max_length=10,
            ),
        ),
    ]
