# Generated by Django 5.2.4 on 2025-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_demand_allocation_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="demand_completion_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="demandeditrequest",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
