# Generated by Django 5.2.4 on 2025-09-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_demand_demand_completion_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
