# Generated by Django 5.2.4 on 2025-12-25 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_notifications_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamdailyschedule",
            name="team_capacity",
        ),
    ]
