# Generated by Django 5.2.4 on 2025-12-25 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_teamdailyschedule_team_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacity",
            name="capacity_hours",
            field=models.FloatField(
                default=8.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(15.0),
                ],
            ),
        ),
    ]
