# Generated by Django 5.2.4 on 2025-12-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_capacity_capacity_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demand",
            name="allocation_mode",
        ),
        migrations.AlterField(
            model_name="demand",
            name="demand_completion_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="demandeditrequest",
            name="new_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
